### ISSUE TITLE
Erreur avec NtpClientLib

### ISSUE THREAD

**Issue by nesdnuma** [Hackable-magazine/Hackable29#1]
Bonjour,

Je vous signale que la bibliothèque NtpClientLib demande la présence de la bibliothèque ESPAsyncUDP sinon la  compilation ne s'effectue pas.

**Comment by 0xDRRB** [comment]
En effet. Mais c'est une dépendant de NtpClientLib et donc quelque chose qui devrait être précisé dans le README de cette bibliothèque.
