### ISSUE TITLE
Référence implicite à un article précédent de Hackable magazine

### ISSUE THREAD

**Issue by nesdnuma** [Hackable-magazine/Hackable29#2]
Bonjour,

Il serait utile d'expliciter dans les commentaires du croquis Arduino que les paramètres du réseau doivent être placés préalablement dans l'EPROM et comment le faire.

J'ai retrouvé le croquis ad hoc dans le dossier GitHub lié au n° 26 du magazine et ai réussi à l'utiliser mais en tant qu'acheteur du n° 29 du magazine (et non du n° 26), une explication aurait été utile. On a l'impression que vous vous adressez en priorité à des abonnés, c'est dommage.

**Comment by 0xDRRB** [comment]
Le croquis pour le stockage en EEPROM émulée est présent dans le dépôt, c'est espwifieeprom. Ceci est précisé dans le README.md.

**Comment by nesdnuma** [comment]
Oui, c'est vrai, mais pas dans l'article lui-même (et sans explication sur son fonctionnement...)
