### ISSUE TITLE
Date et heure erronées en début de fonctionnement

### ISSUE THREAD

**Issue by nesdnuma** [Hackable-magazine/Hackable29#3]
Lorsqu'on lance le programme, il y a quelques données qui sont liées à des informations horaires erronées (année 1970). Je suppose que c'est parce que le serveur NTP n'a pas encore été trouvé. Y aurait-il moyen d'empêcher la mémorisation de données tant que la connexion avec le serveur n'est pas assurée?

**Comment by 0xDRRB** [comment]
Il est possible d'utiliser getLastNTPSync() pour obtenir une valeur de type time_t (généralement un long int) correspondant à la dernière synchronisation réussie. On pourrait donc utiliser cette valeur pour déterminer si la date/heure est valide.

**Comment by nesdnuma** [comment]
OK! Merci
