### ISSUE TITLE
Parfois le graphe est vide

### ISSUE THREAD

**Issue by nesdnuma** [Hackable-magazine/Hackable29#4]
Il arrive fréquemment que le graphe soit vide. Les axes et la légende s'affichent correctement, mais aucune donnée n'apparaît. Cela semble se produire aléatoirement. Y aurait-il trop de données à afficher?

**Comment by 0xDRRB** [comment]
J'ai aussi rencontré ce problème, avec une ancienne version de Chromium. Le graph n'est pas réellement vide, si on clique sur l'une des légendes, le graph se redessine correctement. Il en va de même en redimensionnant la fenêtre du navigateur, même légèrement. Je pense que c'est lié au moteur JS du navigateur. Malheureusement, il y a actuellement quelques 420 issues ouvertes sur le dépôt GitHub de Chart.js, la réponse est peut-être noyé dedans, quelque part.

**Comment by nesdnuma** [comment]
Merci!
